// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import LinkCopyController from './link_copy_controller'
application.register('link-copy', LinkCopyController)
