RSpec.describe EditionsController, type: :request do
  # include IntegrationSpecHelpers
  # include Rails.application.routes.url_helpers

  describe "#create" do
    let(:title) { "Some Title" }

    let(:document) { create(:document, :pension) }
    let!(:original_edition) { create(:edition, :pension, document: document, title:) }

    let(:document_attributes) do
      {
        block_type: "pension",
      }.with_indifferent_access
    end
    let(:details) do
      {
        "foo" => "Foo text",
        "bar" => "Bar text",
      }
    end
    let(:organisation) { build(:organisation) }

    let!(:schema) { stub_request_for_schema("pension") }

    before do
      document.latest_published_edition = original_edition
      document.save!
      allow(Organisation).to receive(:all).and_return([organisation])
      allow(Document).to receive(:find).and_return(document)
    end

    describe "when updating an existing block" do
      it "creates a new content block with params generated by the schema" do
        assert_changes -> { document.editions.count }, from: 1, to: 2 do
          assert_changes -> { Version.count }, from: 1, to: 2 do
            post document_editions_path(document), params: {
              something: "else",
              "edition": {
                document_attributes:,
                details:,
                lead_organisation_id: organisation.id,
                title:,
              },
            }
          end
        end

        document.reload
        new_edition = document.editions.last
        new_author = EditionAuthor.last
        new_version = Version.last

        expect(document.block_type).to eq(document_attributes.[](:block_type))
        expect(new_edition.title).to eq(title)
        expect(new_edition.details).to eq(details)

        expect(document.id).to eq(new_edition.document_id)
        expect(new_author.user).to eq(new_edition.creator)
        expect(new_author.user_id).to eq(new_version.whodunnit.to_i)
      end

      it "should render the template when a validation error is raised" do
        renders_errors do
          post document_editions_path(document), params: {
            "edition": {
              document_attributes: {
                block_type: "pension",
              },
            },
          }

          expect(document.title).to eq(assigns(:title))
        end
      end

      it "redirects to the review links step when successful" do
        redirects_to_step(:review_links) do
          post document_editions_path(document), params: {
            "edition": {
              document_attributes: {
                block_type: "pension",
              },
            },
          }
        end
      end

      describe "when subschemas are present" do
        let(:group) { nil }
        let(:subschemas) { [double("subschema", id: "my_subschema_name", group:)] }
        let!(:schema) { stub_request_for_schema("pension", subschemas:) }

        before do
          allow_any_instance_of(Edition).to receive(:has_entries_for_subschema_id?).with("my_subschema_name").and_return(true)
        end

        it "redirects to the first subschema step when successful" do
          redirects_to_step(:embedded_my_subschema_name) do
            post document_editions_path(document), params: {
              "edition": {
                document_attributes: {
                  block_type: "pension",
                },
              },
            }
          end
        end

        describe "when a subschema has a group" do
          let(:group) { "group" }

          it "redirects to the group step when successful" do
            redirects_to_step(:group_group) do
              post document_editions_path(document), params: {
                "edition": {
                  document_attributes: {
                    block_type: "pension",
                  },
                },
              }
            end
          end
        end
      end
    end

    describe "when creating a new block" do
      before do
        allow_any_instance_of(Document).to receive(:is_new_block?).and_return(true)
      end

      it "creates a new content block with params generated by the schema" do
        post editions_path, params: {
          something: "else",
          "edition": {
            document_attributes:,
            details:,
            title:,
            lead_organisation_id: organisation.id,
          },
        }

        edition = Edition.last
        document = edition.document
        author = EditionAuthor.last
        version = Version.last

        expect(edition.title).to eq(title)
        expect(document.block_type).to eq(document_attributes.[](:block_type))
        expect(edition.details).to eq(details)

        expect(document.id).to eq(edition.document_id)
        expect(author.user).to eq(edition.creator)

        expect(author.user_id).to eq(version.whodunnit.to_i)
      end

      it "should render the template when a validation error is raised" do
        renders_errors do
          post editions_path, params: {
            something: "else",
            "edition": {
              document_attributes:,
              details:,
              organisation_id: organisation.id,
            },
          }

          expect("Create content block").to eq(assigns(:title))
        end
      end

      it "redirects to the review step when successful" do
        redirects_to_step(:review) do
          post editions_path, params: {
            something: "else",
            "edition": {
              document_attributes:,
              details:,
              organisation_id: organisation.id,
            },
          }
        end
      end

      describe "when subschemas are present" do
        let(:group) { nil }
        let(:subschemas) { [double("subschema", id: "my_subschema_name", group:)] }
        let!(:schema) { stub_request_for_schema("pension", subschemas:) }

        it "redirects to the first subschema step when successful" do
          redirects_to_step(:embedded_my_subschema_name) do
            post editions_path, params: {
              something: "else",
              "edition": {
                document_attributes:,
                details:,
                organisation_id: organisation.id,
              },
            }
          end
        end

        describe "when a subschema has a group" do
          let(:group) { "group" }

          it "redirects to the group step when successful" do
            redirects_to_step(:group_group) do
              post editions_path, params: {
                something: "else",
                "edition": {
                  document_attributes:,
                  details:,
                  organisation_id: organisation.id,
                },
              }
            end
          end
        end
      end
    end
  end

  def renders_errors(&block)
    edition = build(:edition, :pension, document: document)
    allow_any_instance_of(CreateEditionService).to receive(:call).and_raise(ActiveRecord::RecordInvalid, edition)
    block.call
    expect(response).to render_template("editions/new")
  end

  def redirects_to_step(step, &block)
    edition = build(:edition, :pension, id: 123)
    allow_any_instance_of(CreateEditionService).to receive(:call).and_return(edition)
    block.call
    expect(response).to redirect_to(workflow_path(id: edition.id, step:))
  end
end
