schemas:
  content_block_time_period:
    subschemas:
      date_range:
  content_block_pension:
    fields:
      description:
    subschemas:
      rates:
        fields:
          description:
          amount:
  content_block_contact:
    fields:
      description:

    subschemas:
      email_addresses:
        group: contact_methods
        group_order: 2
        fields:
          description:
            govspeak_enabled: true
      telephones:
        group: contact_methods
        group_order: 3
        fields:
          description:
          opening_hours:
            show_field_name: show_opening_hours
            fields:
              show_opening_hours:
                hidden_field: true
          call_charges:
            show_field_name: show_call_charges_info_url
            fields:
              show_call_charges_info_url:
                hidden_field: true
          bsl_guidance:
            show_field_name: show
            fields:
              show:
                hidden_field: true
          video_relay_service:
            show_field_name: show
            fields:
              show:
                hidden_field: true
          telephone_numbers:
      addresses:
        group: contact_methods
        group_order: 1
      contact_links:
        group: contact_methods
        group_order: 4
  content_block_tax:
    subschemas:
      things_taxed:
        fields:
          rates:
            fields:
              bands:
                fields:
                  lower_threshold:
                    show_field_name: show
                    fields:
                      show:
                        hidden_field: true
                  upper_threshold:
                    show_field_name: show
                    fields:
                      show:
                        hidden_field: true
