schemas:
  content_block_pension:
    fields:
      description:
        component:
          textarea
        govspeak_enabled: true
    subschemas:
      rates:
        embeddable_fields:
          - amount
        field_order:
          - title
          - amount
          - frequency
          - description
        fields:
          description:
            component:
              textarea
            govspeak_enabled: true
  content_block_contact:
    embeddable_as_block: true
    field_order:
      - title
      - description
      - contact_type
    fields:
      description:
        component:
          textarea
        govspeak_enabled: true

    subschemas:
      email_addresses:
        group: contact_methods
        group_order: 2
        embeddable_as_block: true
        embeddable_fields:
          - email_address
        field_order:
          - title
          - label
          - email_address
          - subject
          - body
          - description
        fields:
          body:
            component:
              textarea
          description:
            component:
              textarea
            govspeak_enabled: true
      telephones:
        group: contact_methods
        group_order: 3
        embeddable_as_block: true
        embeddable_fields:
          - telephone_numbers
          - video_relay_service
          - opening_hours
          - call_charges
          - bsl_guidance
        field_order:
          - title
          - description
          - telephone_numbers
          - video_relay_service
          - bsl_guidance
          - opening_hours
          - call_charges
        fields:
          description:
            component:
              textarea
            govspeak_enabled: true
          opening_hours:
            component:
              opening_hours
            fields:
              opening_hours:
                govspeak_enabled: true
          call_charges:
            component:
              call_charges
          bsl_guidance:
            component:
              bsl_guidance
            fields:
              value:
                govspeak_enabled: true
          video_relay_service:
            component:
              video_relay_service
            fields:
              prefix:
                govspeak_enabled: true
          telephone_numbers:
            field_order:
              - type
              - label
              - telephone_number
      addresses:
        group: contact_methods
        group_order: 1
        field_order:
          - title
          - recipient
          - street_address
          - town_or_city
          - state_or_county
          - postal_code
          - country
          - description
        embeddable_as_block: true
        embeddable_fields:
          - title
          - street_address
          - town_or_city
          - state_or_county
          - postal_code
          - country
          - description
        fields:
          country:
            component:
              country
          description:
            component:
              textarea
            govspeak_enabled: true
      contact_links:
        group: contact_methods
        embeddable_as_block: true
        group_order: 4
        fields:
          description:
            component:
              textarea
        embeddable_fields:
          - url
        field_order:
          - title
          - label
          - url
          - description

