name: combine-coverage.yml
on: workflow_call

jobs:
  combine-coverage:
    name: Combine coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          show-progress: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - name: Download coverage
        uses: actions/download-artifact@v8
        with:
          pattern: "*-coverage-*"
          path: coverage/
      - name: Check coverage
        env:
          MINIMUM_COVERAGE: 99.40
        run: bundle exec rake check_coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: coverage
          path: coverage/
          include-hidden-files: true
