name: combine-coverage.yml
on: workflow_call

jobs:
  combine-coverage:
    name: Combine coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          show-progress: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true
      - name: Download coverage
        uses: actions/download-artifact@v8
        with:
          pattern: "*-coverage-*"
          path: coverage/
      - name: Check coverage
        env:
          MINIMUM_COVERAGE: 99.40
        run: bundle exec rake check_coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: coverage
          path: coverage/
          include-hidden-files: true
