name: Run erblint

on: workflow_call

jobs:
  run-erb-lint:
    name: Run ERB lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          bundler-cache: true

      - name: Run erblint
        run: bundle exec erblint --lint-all
