name: Run erblint

on: workflow_call

jobs:
  run-erb-lint:
    name: Run ERB lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          bundler-cache: true

      - name: Run erblint
        run: bundle exec erblint --lint-all
